################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Bump.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/Bump.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Bump.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Clock.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/Clock.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Clock.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

CortexM.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/CortexM.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="CortexM.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LaunchPad.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/LaunchPad.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="LaunchPad.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Motor.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/Motor.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Motor.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

PWM.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/PWM.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="PWM.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

SSD1306.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/SSD1306.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="SSD1306.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

TA3InputCapture.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/TA3InputCapture.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="TA3InputCapture.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Tachometer.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/Tachometer.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Tachometer.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Timer32.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/Timer32.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="Timer32.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

TimerA1.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/TimerA1.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="TimerA1.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

blinker.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/blinker.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="blinker.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

board.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/board.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="board.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

cpu.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/driverlib/cpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="cpu.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

device.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/device.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="device.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driver.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/driver.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="driver.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fixed.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/fixed.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="fixed.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

flowcont.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/flowcont.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="flowcont.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fpu.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/driverlib/fpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="fpu.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fs.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/fs.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="fs.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

interrupt.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/driverlib/interrupt.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="interrupt.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

netapp.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/netapp.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="netapp.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

netcfg.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/netcfg.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="netcfg.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

nonos.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/nonos.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="nonos.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

odometry.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/inc/odometry.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="odometry.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

socket.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/socket.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="socket.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

spawn.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/spawn.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="spawn.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

spi.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/spi.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="spi.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sysctl.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/driverlib/sysctl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="sysctl.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

timer_tick.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/timer_tick.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="timer_tick.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ustdlib.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/utils/ustdlib.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ustdlib.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

wlan.obj: C:/Users/Bilge/Documents/College\ Documents/ece\ 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/wlan.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/Lab20_CC3100" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/driverlib" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Bilge/Documents/College Documents/ece 3501_embedded/tirslk_max_1_00_00/inc" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="wlan.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


